-- Pembuatan Tabel Master Pagu Anggaran
CREATE TABLE IF NOT EXISTS public.gov_pagu_anggaran (
    id bigint generated by default as identity primary key,
    tahun_anggaran text not null,
    unit_id bigint references public.gov_units(id) on delete cascade,
    nominal numeric default 0,
    sumber_dana text,
    keterangan text,
    status_pagu text,
    jenis_anggaran text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pembuatan Tabel Master Realisasi Anggaran
CREATE TABLE IF NOT EXISTS public.gov_realisasi_anggaran (
    id bigint generated by default as identity primary key,
    tahun_anggaran text not null,
    unit_id bigint references public.gov_units(id) on delete cascade,
    sumber_dana text,
    realisasi numeric default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Konfigurasi RLS (Row Level Security) agar bisa diakses secara publik (atau sesuai policy Supabase yang berlaku)
ALTER TABLE public.gov_pagu_anggaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gov_realisasi_anggaran ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated full access for gov_pagu_anggaran" ON public.gov_pagu_anggaran
FOR ALL TO authenticated USING (true);

CREATE POLICY "Allow public read access for gov_pagu_anggaran" ON public.gov_pagu_anggaran
FOR SELECT TO anon USING (true);

CREATE POLICY "Allow authenticated full access for gov_realisasi_anggaran" ON public.gov_realisasi_anggaran
FOR ALL TO authenticated USING (true);

CREATE POLICY "Allow public read access for gov_realisasi_anggaran" ON public.gov_realisasi_anggaran
FOR SELECT TO anon USING (true);

-- Notifikasi pergerakan skema ke PostgREST
NOTIFY pgrst, 'reload schema';
