-- ====================================================================
-- SCRIPT MIGRASI DATABASE SUPABASE: MODUL RKA PENERIMAAN (RKAT PENERIMAAN)
-- Target Database: Supabase SQL Editor
-- ====================================================================

-- 1. Buat / Update Tabel Utama 'rkat_penerimaan'
CREATE TABLE IF NOT EXISTS public.rkat_penerimaan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renterima_id BIGINT,
    unit_kerja TEXT NOT NULL,
    nama_akun_penerimaan TEXT NOT NULL,
    tahun INT DEFAULT 2027,
    renterima_is_aktif INT DEFAULT 1,
    renterima_volume NUMERIC(18,2) DEFAULT 0,
    renterima_tarif NUMERIC(18,2) DEFAULT 0,
    renterima_jumlah NUMERIC(18,2) DEFAULT 0,
    renterima_pagu NUMERIC(18,2) DEFAULT 0,
    status TEXT DEFAULT 'Sedang Diproses',
    keterangan TEXT,
    sumber_dana TEXT DEFAULT 'Dana Masyarakat Tidak Mengikat',
    
    -- Kolom Klasifikasi & Format Laporan Penerimaan
    kelompok_penerimaan TEXT,
    format_proposal TEXT,
    tags JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tambah kolom klasifikasi jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.rkat_penerimaan ADD COLUMN IF NOT EXISTS kelompok_penerimaan TEXT;
ALTER TABLE public.rkat_penerimaan ADD COLUMN IF NOT EXISTS format_proposal TEXT;
ALTER TABLE public.rkat_penerimaan ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '{}'::jsonb;

-- Tambah kolom 'modul' pada master 'rka_rules' agar mendukung Rule Pengeluaran & Penerimaan
ALTER TABLE public.rka_rules ADD COLUMN IF NOT EXISTS modul TEXT DEFAULT 'pengeluaran';

-- 2. Indeks Performa untuk Pencarian & Filter
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_tahun ON public.rkat_penerimaan(tahun);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_unit ON public.rkat_penerimaan(unit_kerja);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_akun ON public.rkat_penerimaan(nama_akun_penerimaan);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_renterima_id ON public.rkat_penerimaan(renterima_id);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_status ON public.rkat_penerimaan(status);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_format ON public.rkat_penerimaan(format_proposal);
CREATE INDEX IF NOT EXISTS idx_rka_rules_modul ON public.rka_rules(modul);

-- 3. Konfigurasi Row Level Security (RLS) & Policies
ALTER TABLE public.rkat_penerimaan ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to rkat_penerimaan" ON public.rkat_penerimaan;
CREATE POLICY "Allow all access to rkat_penerimaan" ON public.rkat_penerimaan FOR ALL USING (true) WITH CHECK (true);

-- 4. Seed Data Contoh (Fakultas Ilmu Budaya TA 2027)
INSERT INTO public.rkat_penerimaan (
    renterima_id,
    unit_kerja,
    nama_akun_penerimaan,
    tahun,
    renterima_is_aktif,
    renterima_volume,
    renterima_tarif,
    renterima_jumlah,
    renterima_pagu,
    status,
    keterangan,
    sumber_dana,
    format_proposal,
    kelompok_penerimaan
) VALUES (
    114717,
    '08000010 Fakultas Ilmu Budaya',
    '41101.04.03.02 Penerimaan UKT S1 | UKT Pendidikan Unggul Bersubsidi 25%',
    2027,
    1,
    24,
    5700000.00,
    136800000.00,
    136800000.00,
    'Sedang Diproses',
    'S1 BAHASA DAN SASTRA INDONESIA - tahun anggaran 2027 - angkatan 2026',
    'Dana Masyarakat Tidak Mengikat',
    'Penerimaan UKT Sarjana (S1)',
    'Pendapatan Layanan Pendidikan'
) ON CONFLICT DO NOTHING;

-- 5. Seed Rules Awal untuk Modul Penerimaan
INSERT INTO public.rka_rules (priority, modul, unit, akun, kata_kunci, target_field, nilai_klasifikasi, keterangan)
VALUES 
(1, 'penerimaan', '*', '41101.04*', 'UKT', 'format_proposal', 'Penerimaan UKT Sarjana (S1)', 'Klasifikasi penerimaan UKT Program Sarjana'),
(2, 'penerimaan', '*', '41101.05*', 'UKT', 'format_proposal', 'Penerimaan UKT Vokasi / Terapan', 'Klasifikasi penerimaan UKT Sarjana Terapan / Diploma'),
(3, 'penerimaan', '*', '41102*', 'IPI|Mandiri', 'format_proposal', 'Iuran Pengembangan Institusi (IPI)', 'Klasifikasi penerimaan seleksi mandiri / IPI'),
(4, 'penerimaan', '*', '41101*', 'Pascasarjana|Magister|Doktor|S2|S3', 'format_proposal', 'Penerimaan Pascasarjana & Profesi', 'Klasifikasi penerimaan UKT/SPP S2 & S3'),
(5, 'penerimaan', '*', '412*', 'Kerjasama|Riset|Penelitian|Hibah', 'format_proposal', 'Penerimaan Kerjasama & Hibah Riset', 'Klasifikasi dana kerjasama penelitian dan pengabdian'),
(6, 'penerimaan', '*', '413*', 'Sewa|Kantin|Usaha|Komersial', 'format_proposal', 'Penerimaan Hasil Usaha & Layanan Bisnis', 'Klasifikasi pemanfaatan aset dan unit usaha');
