-- ====================================================================
-- SCRIPT MIGRASI DATABASE SUPABASE: REVIEW ANGGARAN & RULE ENGINE
-- Target Database: Supabase SQL Editor
-- ====================================================================

-- 1. Buat Tabel 'rules' (Master Aturan Penguncian)
CREATE TABLE IF NOT EXISTS public.rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority INT DEFAULT 99,
    unitkerja_nama TEXT,
    akun TEXT,
    kata_kunci_deskripsi TEXT,
    operator TEXT DEFAULT 'CONTAINS',
    custom_status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Buat Tabel 'budgets' (Data Usulan Anggaran Smart Budget Review)
CREATE TABLE IF NOT EXISTS public.budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_db TEXT,
    unitkerja_nama TEXT NOT NULL,
    akun TEXT NOT NULL,
    komponen_nama TEXT,
    deskripsi TEXT NOT NULL,
    lingkup TEXT,
    maksud_tujuan TEXT,
    vol NUMERIC DEFAULT 1,
    tarif NUMERIC DEFAULT 0,
    total NUMERIC DEFAULT 0,
    kunci VARCHAR(10) DEFAULT 'N',
    kunci_by VARCHAR(50),
    custom_status TEXT,
    ai_confidence NUMERIC,
    ai_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tambahkan Kolom Baru & Constraint UNIQUE 'id_db' Jika Tabel Sudah Ada
ALTER TABLE public.budgets ADD COLUMN IF NOT EXISTS id_db TEXT;
ALTER TABLE public.budgets ADD COLUMN IF NOT EXISTS vol NUMERIC DEFAULT 1;
ALTER TABLE public.budgets ADD COLUMN IF NOT EXISTS tarif NUMERIC DEFAULT 0;
ALTER TABLE public.budgets DROP CONSTRAINT IF EXISTS budgets_id_db_key;
ALTER TABLE public.budgets ADD CONSTRAINT budgets_id_db_key UNIQUE (id_db);

-- 4. Atur Hak Akses (Row Level Security & Policies)
ALTER TABLE public.rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to rules" ON public.rules;
CREATE POLICY "Allow all access to rules" ON public.rules FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all access to budgets" ON public.budgets;
CREATE POLICY "Allow all access to budgets" ON public.budgets FOR ALL USING (true) WITH CHECK (true);
