-- =========================================================================
-- TABEL PENYESUAIAN RKA (PENGELUARAN & PENERIMAAN)
-- Mencatat penyesuaian (+ / -) pagu anggaran untuk komparasi & laporan resmi
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.rkat_penyesuaian (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modul TEXT NOT NULL DEFAULT 'pengeluaran',      -- 'pengeluaran' atau 'penerimaan'
  tahun_anggaran INT NOT NULL DEFAULT 2027,
  versi_anggaran TEXT NOT NULL DEFAULT 'v1',       -- 'v1', 'v2', dst
  unit_kerja TEXT NOT NULL,
  kode_akun TEXT,
  nama_akun TEXT NOT NULL,
  uraian TEXT NOT NULL,
  pagu_semula NUMERIC(18,2) DEFAULT 0,
  jenis_penyesuaian TEXT NOT NULL DEFAULT 'tambah', -- 'tambah' | 'kurang' | 'pergeseran'
  nilai_penyesuaian NUMERIC(18,2) NOT NULL DEFAULT 0, -- nominal penyesuaian (+/-)
  pagu_setelah NUMERIC(18,2) NOT NULL DEFAULT 0,      -- pagu akhir setelah disesuaikan
  no_sk TEXT,                                     -- nomor SK / dasar penyesuaian
  tanggal_sk DATE,
  keterangan TEXT,
  target_laporan TEXT NOT NULL DEFAULT 'semua',   -- 'semua' | 'proposal rkat' | 'laporan_kementerian' | 'laporan_webometrics'
  referensi_id BIGINT,                            -- ID rkat_pengeluaran atau rkat_penerimaan jika terhubung
  created_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tambah kolom jika tabel sudah terlanjur dibuat sebelumnya:
ALTER TABLE public.rkat_penyesuaian ADD COLUMN IF NOT EXISTS target_laporan TEXT DEFAULT 'semua';

-- Row Level Security
ALTER TABLE public.rkat_penyesuaian ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to rkat_penyesuaian" ON public.rkat_penyesuaian;
CREATE POLICY "Allow all access to rkat_penyesuaian" ON public.rkat_penyesuaian FOR ALL USING (true) WITH CHECK (true);

-- Indexes untuk pencarian & agregasi cepat di laporan
CREATE INDEX IF NOT EXISTS idx_rkat_penyesuaian_modul_tahun_versi 
ON public.rkat_penyesuaian(modul, tahun_anggaran, versi_anggaran);

CREATE INDEX IF NOT EXISTS idx_rkat_penyesuaian_unit 
ON public.rkat_penyesuaian(unit_kerja);

NOTIFY pgrst, 'reload schema';
