-- =========================================================================
-- MIGRASI DATABASE SUPABASE: rkat_realisasi_tahunan
-- Tabel untuk menampung data Realisasi Tahunan (N-2) & Anggaran Tahunan (N-1)
-- Untuk pelaporan PTN-BH Kementerian (Template Laporan 2: Sheet 3, 4, 6, 7)
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.rkat_realisasi_tahunan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tahun INT NOT NULL,                                           -- 2024 (Realisasi N-2), 2025 (Anggaran N-1), dsb
  jenis VARCHAR(50) NOT NULL DEFAULT 'realisasi',               -- 'realisasi' | 'anggaran' | 'prognosa'
  kategori VARCHAR(50) NOT NULL,                                -- 'komponen_biaya' | 'sumber_pembiayaan'
  sheet_no VARCHAR(20) NOT NULL,                                -- '3', '4', '6', '7'
  kode_pos VARCHAR(100) NOT NULL,                               -- 'operasional', 'dosen_asn', 'investasi', 'bpptnbh', dll
  nama_pos VARCHAR(255) NOT NULL,                               -- Nama tampilan komponen/sumber
  sub_pos VARCHAR(255) NOT NULL DEFAULT '',                     -- Sub-rincian (contoh: 'a. Prime Step ADB')
  sumber_dana VARCHAR(100) NOT NULL DEFAULT 'ALL',              -- Untuk Rincian Sheet 6: 'dukman', 'bpptnbh', 'selain_apbn', dll
  nilai NUMERIC(20, 2) NOT NULL DEFAULT 0,                      -- Nilai pagu/realisasi dalam Rupiah
  proporsi NUMERIC(8, 4) DEFAULT 0,                             -- Proporsi % jika relevan
  satuan VARCHAR(50) DEFAULT 'Rupiah',
  keterangan TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  CONSTRAINT uq_rkat_realisasi_tahunan UNIQUE (tahun, jenis, sheet_no, kode_pos, sub_pos, sumber_dana)
);

-- Row Level Security (RLS)
ALTER TABLE public.rkat_realisasi_tahunan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to rkat_realisasi_tahunan" ON public.rkat_realisasi_tahunan;
CREATE POLICY "Allow all access to rkat_realisasi_tahunan" ON public.rkat_realisasi_tahunan FOR ALL USING (true) WITH CHECK (true);

-- Indexes untuk akselerasi query pelaporan
CREATE INDEX IF NOT EXISTS idx_rkat_realisasi_tahun_jenis 
ON public.rkat_realisasi_tahunan(tahun, jenis);

CREATE INDEX IF NOT EXISTS idx_rkat_realisasi_sheet_kategori 
ON public.rkat_realisasi_tahunan(sheet_no, kategori);

-- =========================================================================
-- SEED DATA AWAL: Sheet 3 (Ringkasan Biaya)
-- Realisasi 2024 (N-2) & Anggaran 2025 (N-1)
-- =========================================================================
INSERT INTO public.rkat_realisasi_tahunan 
  (tahun, jenis, kategori, sheet_no, kode_pos, nama_pos, sub_pos, sumber_dana, nilai, keterangan)
VALUES
  -- 2024: Realisasi N-2 (Sheet 3)
  (2024, 'realisasi', 'komponen_biaya', '3', 'operasional', 'Biaya Operasional', '', 'ALL', 1850000000000, 'Realisasi Operasional TA 2024'),
  (2024, 'realisasi', 'komponen_biaya', '3', 'dosen_pns', 'Biaya Dosen PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 245000000000, 'Realisasi Gaji & Tunj Dosen PNS 2024'),
  (2024, 'realisasi', 'komponen_biaya', '3', 'tendik_pns', 'Biaya Tenaga Kependidikan PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 238000000000, 'Realisasi Gaji & Tunj Tendik PNS 2024'),
  (2024, 'realisasi', 'komponen_biaya', '3', 'dosen_non_pns', 'Biaya Dosen Non PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 95000000000, 'Realisasi Dosen Tetap Non PNS 2024'),
  (2024, 'realisasi', 'komponen_biaya', '3', 'tendik_non_pns', 'Biaya Tenaga Kependidikan Non PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 140000000000, 'Realisasi Tendik Non PNS 2024'),
  (2024, 'realisasi', 'komponen_biaya', '3', 'remunerasi', 'Remunerasi/Imbal Jasa/Insentif/Sejenisnya', '', 'ALL', 320000000000, 'Realisasi Remunerasi & Insentif 2024'),
  (2024, 'realisasi', 'komponen_biaya', '3', 'investasi', 'Biaya Investasi (Prasarana dan Sarana)', '', 'ALL', 285000000000, 'Realisasi Belanja Modal & Sarpras 2024'),
  (2024, 'realisasi', 'komponen_biaya', '3', 'pengembangan', 'Biaya Pengembangan', '', 'ALL', 110000000000, 'Realisasi Tridharma & Riset 2024'),

  -- 2025: Anggaran N-1 (Sheet 3)
  (2025, 'anggaran', 'komponen_biaya', '3', 'operasional', 'Biaya Operasional', '', 'ALL', 1980000000000, 'Pagu Anggaran Operasional TA 2025'),
  (2025, 'anggaran', 'komponen_biaya', '3', 'dosen_pns', 'Biaya Dosen PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 250000000000, 'Pagu Gaji & Tunj Dosen PNS 2025'),
  (2025, 'anggaran', 'komponen_biaya', '3', 'tendik_pns', 'Biaya Tenaga Kependidikan PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 244508254000, 'Pagu Gaji & Tunj Tendik PNS 2025'),
  (2025, 'anggaran', 'komponen_biaya', '3', 'dosen_non_pns', 'Biaya Dosen Non PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 105000000000, 'Pagu Dosen Tetap Non PNS 2025'),
  (2025, 'anggaran', 'komponen_biaya', '3', 'tendik_non_pns', 'Biaya Tenaga Kependidikan Non PNS (gaji dan tunjangan yang melekat pada gaji)', '', 'ALL', 152000000000, 'Pagu Tendik Non PNS 2025'),
  (2025, 'anggaran', 'komponen_biaya', '3', 'remunerasi', 'Remunerasi/Imbal Jasa/Insentif/Sejenisnya', '', 'ALL', 345000000000, 'Pagu Remunerasi & Insentif 2025'),
  (2025, 'anggaran', 'komponen_biaya', '3', 'investasi', 'Biaya Investasi (Prasarana dan Sarana)', '', 'ALL', 310000000000, 'Pagu Belanja Modal Sarpras 2025'),
  (2025, 'anggaran', 'komponen_biaya', '3', 'pengembangan', 'Biaya Pengembangan', '', 'ALL', 125000000000, 'Pagu Pengembangan Tridharma 2025')
ON CONFLICT (tahun, jenis, sheet_no, kode_pos, sub_pos, sumber_dana) 
DO UPDATE SET 
  nilai = EXCLUDED.nilai,
  nama_pos = EXCLUDED.nama_pos,
  keterangan = EXCLUDED.keterangan,
  updated_at = timezone('utc'::text, now());

-- =========================================================================
-- SEED DATA AWAL: Sheet 4 (Ringkasan Sumber Pembiayaan)
-- =========================================================================
INSERT INTO public.rkat_realisasi_tahunan 
  (tahun, jenis, kategori, sheet_no, kode_pos, nama_pos, sub_pos, sumber_dana, nilai, keterangan)
VALUES
  -- 2024: Realisasi N-2 (Sheet 4 - APBN & Selain APBN)
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'dukman', '(7734) Dukungan Manajemen Ditjen Dikti', '', 'APBN', 483000000000, 'RM Gaji PNS 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'bpptnbh', 'Alokasi BPPTNBH', '', 'APBN', 165000000000, 'BPPTNBH 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'iku', 'Bantuan Pendanaan Berbasis IKU', '', 'APBN', 22000000000, 'IKU 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'puapt', 'PUAPT/PRPTNBH', '', 'APBN', 0, 'PUAPT 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'pln_hln', 'PLN/HLN/RMP/SBSN/KPBU', '', 'APBN', 45000000000, 'Pinjaman LN 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'dikti_lain', 'Pendanaan Lainnya dari Ditjen Dikti', '', 'APBN', 115000000000, 'Ditjen Dikti Lain 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'kl_lain', 'Pendanaan dari K/L lain (termasuk LPDP)', '', 'APBN', 72000000000, 'K/L Lain 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'dana_masyarakat', 'Dana Masyarakat', '', 'SELAIN APBN', 2150000000000, 'Penerimaan Masyarakat 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'biaya_pendidikan', 'Biaya Pendidikan (UKT, IPI)', '', 'SELAIN APBN', 1620000000000, 'UKT & IPI 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'dana_abadi', 'Pengelolaan Dana Abadi', '', 'SELAIN APBN', 28000000000, 'Hasil Dana Abadi 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'usaha_ptnbh', 'Usaha PTN Badan Hukum', '', 'SELAIN APBN', 85000000000, 'Usaha Komersial 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'kerjasama', 'Kerjasama Tridharma Perguruan Tinggi', '', 'SELAIN APBN', 380000000000, 'Kontrak Kerjasama 2024'),
  (2024, 'realisasi', 'sumber_pembiayaan', '4', 'saldo_kas', 'Saldo Kas Awal', '', 'SELAIN APBN', 120000000000, 'Saldo Awal 2024'),

  -- 2025: Anggaran N-1 (Sheet 4 - APBN & Selain APBN)
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'dukman', '(7734) Dukungan Manajemen Ditjen Dikti', '', 'APBN', 494508254000, 'RM Gaji PNS 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'bpptnbh', 'Alokasi BPPTNBH', '', 'APBN', 172942300000, 'BPPTNBH 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'iku', 'Bantuan Pendanaan Berbasis IKU', '', 'APBN', 25000000000, 'IKU 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'puapt', 'PUAPT/PRPTNBH', '', 'APBN', 0, 'PUAPT 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'pln_hln', 'PLN/HLN/RMP/SBSN/KPBU', '', 'APBN', 48070000000, 'Prime Step ADB 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'dikti_lain', 'Pendanaan Lainnya dari Ditjen Dikti', '', 'APBN', 129713907730, 'Ditjen Dikti Lain 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'kl_lain', 'Pendanaan dari K/L lain (termasuk LPDP)', '', 'APBN', 77200000000, 'K/L Lain 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'dana_masyarakat', 'Dana Masyarakat', '', 'SELAIN APBN', 2280000000000, 'Penerimaan Masyarakat 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'biaya_pendidikan', 'Biaya Pendidikan (UKT, IPI)', '', 'SELAIN APBN', 1710000000000, 'UKT & IPI 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'dana_abadi', 'Pengelolaan Dana Abadi', '', 'SELAIN APBN', 32000000000, 'Hasil Dana Abadi 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'usaha_ptnbh', 'Usaha PTN Badan Hukum', '', 'SELAIN APBN', 95000000000, 'Usaha Komersial 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'kerjasama', 'Kerjasama Tridharma Perguruan Tinggi', '', 'SELAIN APBN', 410000000000, 'Kontrak Kerjasama 2025'),
  (2025, 'anggaran', 'sumber_pembiayaan', '4', 'saldo_kas', 'Saldo Kas Awal', '', 'SELAIN APBN', 150000000000, 'Saldo Awal 2025')
ON CONFLICT (tahun, jenis, sheet_no, kode_pos, sub_pos, sumber_dana) 
DO UPDATE SET 
  nilai = EXCLUDED.nilai,
  nama_pos = EXCLUDED.nama_pos,
  keterangan = EXCLUDED.keterangan,
  updated_at = timezone('utc'::text, now());

-- Reload schema PostgREST Supabase
NOTIFY pgrst, 'reload schema';
