-- ====================================================================
-- SCRIPT MIGRASI DATABASE SUPABASE: MODUL RKA (RKAT PENGELUARAN)
-- Target Database: Supabase SQL Editor
-- ====================================================================

-- 1. Buat Tabel Utama 'rkat_pengeluaran'
CREATE TABLE IF NOT EXISTS public.rkat_pengeluaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tahun_anggaran INT DEFAULT 2027,
    unit TEXT,
    tujuan TEXT,
    sasaran TEXT,
    program TEXT,
    indikator_program TEXT,
    target NUMERIC,
    cascading_kinerja_target_satuan TEXT,
    kelompok_indikator_program TEXT,
    cascading_kinerja_iku TEXT,
    kegiatan TEXT,
    lingkup_kegiatan TEXT,
    sumber_dana_nama TEXT,
    prioritas TEXT,
    akun_utama TEXT,
    sub_akun TEXT,
    akun_detail TEXT,
    uraian_belanja TEXT,
    anggaran NUMERIC(18,2) DEFAULT 0,
    realisasi NUMERIC(18,2) DEFAULT 0,
    rncn_pengeluaran_is_aprove TEXT DEFAULT 'Belum',
    
    -- Kolom Tambahan Identifikasi / Grouping Laporan Khusus
    laporan_kementerian TEXT,
    laporan_webometrics TEXT,
    identifikasi_lain TEXT,
    tags JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Buat Tabel 'rka_rules' (Master Rule Engine Pengelompokan & Identifikasi RKA)
CREATE TABLE IF NOT EXISTS public.rka_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority INT DEFAULT 99,
    unit TEXT DEFAULT '*',
    akun TEXT DEFAULT '*',
    kata_kunci TEXT NOT NULL,
    target_field TEXT DEFAULT 'laporan_kementerian', -- 'laporan_kementerian', 'laporan_webometrics', atau 'identifikasi_lain'
    nilai_klasifikasi TEXT NOT NULL,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Indeks Performa untuk Pencarian & Filter
CREATE INDEX IF NOT EXISTS idx_rkat_pengeluaran_tahun ON public.rkat_pengeluaran(tahun_anggaran);
CREATE INDEX IF NOT EXISTS idx_rkat_pengeluaran_unit ON public.rkat_pengeluaran(unit);
CREATE INDEX IF NOT EXISTS idx_rkat_pengeluaran_akun ON public.rkat_pengeluaran(akun_detail);
CREATE INDEX IF NOT EXISTS idx_rkat_pengeluaran_kemen ON public.rkat_pengeluaran(laporan_kementerian);
CREATE INDEX IF NOT EXISTS idx_rkat_pengeluaran_webo ON public.rkat_pengeluaran(laporan_webometrics);
CREATE INDEX IF NOT EXISTS idx_rka_rules_priority ON public.rka_rules(priority);

-- 4. Konfigurasi Row Level Security (RLS) & Policies
ALTER TABLE public.rkat_pengeluaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rka_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to rkat_pengeluaran" ON public.rkat_pengeluaran;
CREATE POLICY "Allow all access to rkat_pengeluaran" ON public.rkat_pengeluaran FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all access to rka_rules" ON public.rka_rules;
CREATE POLICY "Allow all access to rka_rules" ON public.rka_rules FOR ALL USING (true) WITH CHECK (true);

-- 5. Seed Data Contoh (Fakultas Filsafat TA 2027)
INSERT INTO public.rkat_pengeluaran (
    tahun_anggaran,
    unit,
    tujuan,
    sasaran,
    program,
    indikator_program,
    target,
    cascading_kinerja_target_satuan,
    kelompok_indikator_program,
    cascading_kinerja_iku,
    kegiatan,
    lingkup_kegiatan,
    sumber_dana_nama,
    prioritas,
    akun_utama,
    sub_akun,
    akun_detail,
    uraian_belanja,
    anggaran,
    realisasi,
    rncn_pengeluaran_is_aprove,
    laporan_kementerian,
    laporan_webometrics
) VALUES (
    2027,
    '05000010 Fakultas Filsafat',
    'Mewujudkan pendidikan transdisiplin yang unggul, inovatif inklusif dan aplikatif',
    '1.2.1 Meningkatnya kualitas kurikulum yang inovatif, inklusif, dan aplikatif',
    '1.2.1.1.1 Pengembangan sistem penerimaan mahasiswa yang mengakomodir keberagaman',
    '1.2.1.1.1.25 Jumlah mahasiswa asing semua jenjang (Kredit)',
    11.00,
    'mahasiswa',
    'Rencana Strategis',
    NULL,
    '1.2.1.1.1.25.3 Peningkatan mahasiswa asing bergelar di program studi',
    'Beasiswa bagi mahasiswa asing',
    'Dana Masyarakat Tidak Mengikat',
    'Pertama',
    '52 Belanja Barang dan Jasa',
    '525 Beasiswa, Pemberian Bantuan Tridharma',
    '52501 Beasiswa, Bantuan Tridharma Mahasiswa',
    'Beasiswa, Pemberian Bantuan Tridharma Mahasiswa Asing',
    12000000.00,
    0.00,
    'Belum',
    'Beasiswa Mahasiswa Asing (MBKM / Internasional)',
    'International Student Inbound'
);

-- Seed Data Contoh Rules Klasifikasi Awal
INSERT INTO public.rka_rules (priority, unit, akun, kata_kunci, target_field, nilai_klasifikasi, keterangan)
VALUES 
(1, '*', '52501', 'Mahasiswa Asing', 'laporan_kementerian', 'Beasiswa Mahasiswa Asing (MBKM / Internasional)', 'Otomatis menandai beasiswa mahasiswa internasional'),
(2, '*', '*', 'Mahasiswa Asing', 'laporan_webometrics', 'International Student Inbound', 'Tagging indikator internasionalisasi Webometrics'),
(3, '*', '*', 'Jurnal', 'laporan_kementerian', 'Publikasi Ilmiah & Jurnal Bereputasi', 'Tagging publikasi kementerian'),
(4, '*', '*', 'Website', 'laporan_webometrics', 'Web Visibility & Content', 'Tagging infrastruktur portal web');
