-- =========================================================================
-- MIGRASI MULTI-VERSION BASIS DATA RKA (PENGELUARAN & PENERIMAAN)
-- Menambahkan isolasi versi data (v1 - Murni, v2 - Efisiensi/Perubahan, dst)
-- =========================================================================

-- 1. Tambah kolom versi_anggaran di tabel rkat_pengeluaran
ALTER TABLE public.rkat_pengeluaran 
ADD COLUMN IF NOT EXISTS versi_anggaran TEXT DEFAULT 'v1';

-- Update seluruh data belanja yang ada saat ini menjadi 'v1'
UPDATE public.rkat_pengeluaran 
SET versi_anggaran = 'v1' 
WHERE versi_anggaran IS NULL;

-- Index komposit untuk query cepat per versi dan tahun
CREATE INDEX IF NOT EXISTS idx_rkat_pengeluaran_versi 
ON public.rkat_pengeluaran(versi_anggaran, tahun_anggaran);


-- 2. Tambah kolom versi_anggaran di tabel rkat_penerimaan
ALTER TABLE public.rkat_penerimaan 
ADD COLUMN IF NOT EXISTS versi_anggaran TEXT DEFAULT 'v1';

-- Update seluruh data penerimaan yang ada saat ini menjadi 'v1'
UPDATE public.rkat_penerimaan 
SET versi_anggaran = 'v1' 
WHERE versi_anggaran IS NULL;

-- Index komposit untuk query cepat per versi dan tahun
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_versi 
ON public.rkat_penerimaan(versi_anggaran, tahun);


-- 3. Buat tabel master versi: rka_versi_anggaran
CREATE TABLE IF NOT EXISTS public.rka_versi_anggaran (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_versi TEXT NOT NULL,          -- contoh: 'v1', 'v2', 'v3'
  nama_versi TEXT NOT NULL,          -- contoh: 'v1 - Murni (Penetapan Awal)', 'v2 - Efisiensi'
  tahun_anggaran INT NOT NULL,       -- contoh: 2025
  modul TEXT DEFAULT 'all',          -- 'all', 'pengeluaran', 'penerimaan'
  status TEXT DEFAULT 'aktif',       -- 'aktif', 'terkunci', 'draft'
  keterangan TEXT,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  CONSTRAINT uq_rka_versi UNIQUE(kode_versi, tahun_anggaran, modul)
);

-- Aktifkan RLS
ALTER TABLE public.rka_versi_anggaran ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to rka_versi_anggaran" ON public.rka_versi_anggaran;
CREATE POLICY "Allow all access to rka_versi_anggaran" ON public.rka_versi_anggaran FOR ALL USING (true) WITH CHECK (true);

-- Masukkan versi awal default v1 untuk tahun 2024, 2025, 2026, 2027
INSERT INTO public.rka_versi_anggaran 
  (kode_versi, nama_versi, tahun_anggaran, modul, status, is_default, keterangan)
VALUES 
  ('v1', 'v1 - Murni (Penetapan Awal)', 2024, 'all', 'aktif', true, 'Basis data penetapan awal / usulan kementerian'),
  ('v1', 'v1 - Murni (Penetapan Awal)', 2025, 'all', 'aktif', true, 'Basis data penetapan awal / usulan kementerian'),
  ('v1', 'v1 - Murni (Penetapan Awal)', 2026, 'all', 'aktif', true, 'Basis data penetapan awal / usulan kementerian'),
  ('v1', 'v1 - Murni (Penetapan Awal)', 2027, 'all', 'aktif', true, 'Basis data penetapan awal / usulan kementerian')
ON CONFLICT (kode_versi, tahun_anggaran, modul) DO NOTHING;

-- Notifikasi reload schema cache
NOTIFY pgrst, 'reload schema';
