-- ====================================================================
-- SCRIPT MIGRASI DATABASE SUPABASE: MODUL RKA PENERIMAAN (RKAT PENERIMAAN)
-- Target Database: Supabase SQL Editor
-- ====================================================================

-- 1. Buat Tabel Utama 'rkat_penerimaan'
CREATE TABLE IF NOT EXISTS public.rkat_penerimaan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renterima_id BIGINT,
    unit_kerja TEXT NOT NULL,
    nama_akun_penerimaan TEXT NOT NULL,
    tahun INT DEFAULT 2027,
    renterima_is_aktif INT DEFAULT 1,
    renterima_volume NUMERIC(18,2) DEFAULT 0,
    renterima_tarif NUMERIC(18,2) DEFAULT 0,
    renterima_jumlah NUMERIC(18,2) DEFAULT 0,
    renterima_pagu NUMERIC(18,2) DEFAULT 0,
    status TEXT DEFAULT 'Sedang Diproses',
    keterangan TEXT,
    sumber_dana TEXT DEFAULT 'Dana Masyarakat Tidak Mengikat',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Indeks Performa untuk Pencarian & Filter
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_tahun ON public.rkat_penerimaan(tahun);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_unit ON public.rkat_penerimaan(unit_kerja);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_akun ON public.rkat_penerimaan(nama_akun_penerimaan);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_renterima_id ON public.rkat_penerimaan(renterima_id);
CREATE INDEX IF NOT EXISTS idx_rkat_penerimaan_status ON public.rkat_penerimaan(status);

-- 3. Konfigurasi Row Level Security (RLS) & Policies
ALTER TABLE public.rkat_penerimaan ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to rkat_penerimaan" ON public.rkat_penerimaan;
CREATE POLICY "Allow all access to rkat_penerimaan" ON public.rkat_penerimaan FOR ALL USING (true) WITH CHECK (true);

-- 4. Seed Data Contoh (Fakultas Ilmu Budaya TA 2027)
INSERT INTO public.rkat_penerimaan (
    renterima_id,
    unit_kerja,
    nama_akun_penerimaan,
    tahun,
    renterima_is_aktif,
    renterima_volume,
    renterima_tarif,
    renterima_jumlah,
    renterima_pagu,
    status,
    keterangan,
    sumber_dana
) VALUES (
    114717,
    '08000010 Fakultas Ilmu Budaya',
    '41101.04.03.02 Penerimaan UKT S1 | UKT Pendidikan Unggul Bersubsidi 25%',
    2027,
    1,
    24,
    5700000.00,
    136800000.00,
    136800000.00,
    'Sedang Diproses',
    'S1 BAHASA DAN SASTRA INDONESIA - tahun anggaran 2027 - angkatan 2026',
    'Dana Masyarakat Tidak Mengikat'
);
