"use client";

import React, { useState, useMemo, useEffect } from 'react';
import { 
  Building2, FileSpreadsheet, Eye, EyeOff, Filter, 
  Search, ArrowUpDown, Layers, CheckCircle2, ChevronDown, ChevronRight,
  Download, FileText, Landmark, Wallet, DollarSign, Database, Copy, Check,
  RefreshCw, Server, AlertCircle, Info, Save, Edit3, RotateCcw
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Table, TableHeader, TableBody, TableRow, TableHead, TableCell 
} from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import * as XLSX from 'xlsx';
import toast from 'react-hot-toast';
import { 
  TemplateLaporan2Data,
  computeTemplateLaporan2Data 
} from '@/lib/rka/templateLaporan2Data';

interface TemplateLaporan2ViewProps {
  dataList: any[];
  penyesuaianList: any[];
  tahunFilter: string;
  versiFilter: string;
  formatRp: (val: number) => string;
}

const SQL_MIGRATION_TEXT = `-- SQL MIGRATION SUPABASE: rkat_realisasi_tahunan
CREATE TABLE IF NOT EXISTS public.rkat_realisasi_tahunan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tahun INT NOT NULL,
  jenis VARCHAR(50) NOT NULL DEFAULT 'realisasi',
  kategori VARCHAR(50) NOT NULL,
  sheet_no VARCHAR(20) NOT NULL,
  kode_pos VARCHAR(100) NOT NULL,
  nama_pos VARCHAR(255) NOT NULL,
  sub_pos VARCHAR(255) NOT NULL DEFAULT '',
  sumber_dana VARCHAR(100) NOT NULL DEFAULT 'ALL',
  nilai NUMERIC(20, 2) NOT NULL DEFAULT 0,
  proporsi NUMERIC(8, 4) DEFAULT 0,
  satuan VARCHAR(50) DEFAULT 'Rupiah',
  keterangan TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  CONSTRAINT uq_rkat_realisasi_tahunan UNIQUE (tahun, jenis, sheet_no, kode_pos, sub_pos, sumber_dana)
);

ALTER TABLE public.rkat_realisasi_tahunan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to rkat_realisasi_tahunan" ON public.rkat_realisasi_tahunan;
CREATE POLICY "Allow all access to rkat_realisasi_tahunan" ON public.rkat_realisasi_tahunan FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_rkat_realisasi_tahun_jenis ON public.rkat_realisasi_tahunan(tahun, jenis);
CREATE INDEX IF NOT EXISTS idx_rkat_realisasi_sheet_kategori ON public.rkat_realisasi_tahunan(sheet_no, kategori);
NOTIFY pgrst, 'reload schema';`;

// Template master pos untuk form input
const INITIAL_SHEET3_ITEMS = [
  { no: 1, key: 'operasional', label: 'Biaya Operasional', defN2: 1850000000000, defN1: 1980000000000 },
  { no: 2, key: 'dosen_pns', label: 'Biaya Dosen PNS (gaji & tunjangan melekat)', defN2: 245000000000, defN1: 250000000000 },
  { no: 3, key: 'tendik_pns', label: 'Biaya Tenaga Kependidikan PNS (gaji & tunjangan melekat)', defN2: 238000000000, defN1: 244508254000 },
  { no: 4, key: 'dosen_non_pns', label: 'Biaya Dosen Non PNS (gaji & tunjangan melekat)', defN2: 95000000000, defN1: 105000000000 },
  { no: 5, key: 'tendik_non_pns', label: 'Biaya Tenaga Kependidikan Non PNS (gaji & tunjangan melekat)', defN2: 140000000000, defN1: 152000000000 },
  { no: 6, key: 'remunerasi', label: 'Remunerasi / Imbal Jasa / Insentif', defN2: 320000000000, defN1: 345000000000 },
  { no: 7, key: 'investasi', label: 'Biaya Investasi (Prasarana & Sarana)', defN2: 285000000000, defN1: 310000000000 },
  { no: 8, key: 'pengembangan', label: 'Biaya Pengembangan (Tridharma & Riset)', defN2: 110000000000, defN1: 125000000000 }
];

const INITIAL_SHEET4_ITEMS = [
  { no: 1, key: 'dukman', label: '(7734) Dukungan Manajemen Ditjen Dikti', kategori: 'APBN', defN2: 483000000000, defN1: 494508254000 },
  { no: 2, key: 'bpptnbh', label: 'Alokasi BPPTNBH', kategori: 'APBN', defN2: 165000000000, defN1: 172942300000 },
  { no: 3, key: 'iku', label: 'Bantuan Pendanaan Berbasis IKU', kategori: 'APBN', defN2: 22000000000, defN1: 25000000000 },
  { no: 4, key: 'puapt', label: 'PUAPT / PRPTNBH', kategori: 'APBN', defN2: 0, defN1: 0 },
  { no: 5, key: 'pln_hln', label: 'PLN / HLN / RMP / SBSN / KPBU', kategori: 'APBN', defN2: 45000000000, defN1: 48070000000 },
  { no: 6, key: 'dikti_lain', label: 'Pendanaan Lainnya dari Ditjen Dikti', kategori: 'APBN', defN2: 115000000000, defN1: 129713907730 },
  { no: 7, key: 'eselon_lain', label: 'Pendanaan Unit Eselon I Kemendikbudristek selain Ditjen Dikti', kategori: 'APBN', defN2: 0, defN1: 0 },
  { no: 8, key: 'kl_lain', label: 'Pendanaan dari K/L Lain (termasuk LPDP)', kategori: 'APBN', defN2: 72000000000, defN1: 77200000000 },

  { no: 9, key: 'dana_masyarakat', label: 'Dana Masyarakat', kategori: 'SELAIN APBN', defN2: 2150000000000, defN1: 2280000000000 },
  { no: 10, key: 'biaya_pendidikan', label: 'Biaya Pendidikan (UKT, IPI)', kategori: 'SELAIN APBN', defN2: 1620000000000, defN1: 1710000000000 },
  { no: 11, key: 'dana_abadi', label: 'Pengelolaan Dana Abadi', kategori: 'SELAIN APBN', defN2: 28000000000, defN1: 32000000000 },
  { no: 12, key: 'usaha_ptnbh', label: 'Usaha PTN Badan Hukum', kategori: 'SELAIN APBN', defN2: 85000000000, defN1: 95000000000 },
  { no: 13, key: 'kerjasama', label: 'Kerjasama Tridharma Perguruan Tinggi', kategori: 'SELAIN APBN', defN2: 380000000000, defN1: 410000000000 },
  { no: 14, key: 'kekayaan_ptnbh', label: 'Pengelolaan Kekayaan PTN Badan Hukum', kategori: 'SELAIN APBN', defN2: 22000000000, defN1: 25000000000 },
  { no: 15, key: 'apbd', label: 'APBD', kategori: 'SELAIN APBN', defN2: 0, defN1: 0 },
  { no: 16, key: 'pinjaman', label: 'Pinjaman', kategori: 'SELAIN APBN', defN2: 0, defN1: 0 },
  { no: 17, key: 'saldo_kas', label: 'Saldo Kas', kategori: 'SELAIN APBN', defN2: 120000000000, defN1: 150000000000 }
];

export default function TemplateLaporan2View({
  dataList,
  penyesuaianList,
  tahunFilter,
  versiFilter,
  formatRp
}: TemplateLaporan2ViewProps) {
  // Pilihan Sheet Aktif di Halaman Utama
  const [activeSheet, setActiveSheet] = useState<
    'pengesahan' | 'ringkasan_biaya' | 'ringkasan_sumber' | 'rincian_biaya' | 'rincian_sumber'
  >('pengesahan');

  const [search, setSearch] = useState<string>('');
  const [showDbModal, setShowDbModal] = useState<boolean>(false);
  const [copiedSql, setCopiedSql] = useState<boolean>(false);

  // Tab di dalam Modal: 'input_editor' | 'db_info'
  const [modalTab, setModalTab] = useState<'input_editor' | 'db_info'>('input_editor');
  // Sub-sheet di dalam editor: 'sheet3' | 'sheet4'
  const [editorSubSheet, setEditorSubSheet] = useState<'sheet3' | 'sheet4'>('sheet3');

  // State sinkronisasi database rkat_realisasi_tahunan
  const [realisasiTahunanList, setRealisasiTahunanList] = useState<any[]>([]);
  const [isTableCreated, setIsTableCreated] = useState<boolean>(true);
  const [loadingRealisasi, setLoadingRealisasi] = useState<boolean>(false);
  const [savingRealisasi, setSavingRealisasi] = useState<boolean>(false);

  // State nilai input di editor
  const [formSheet3, setFormSheet3] = useState<{ [key: string]: { n2: number; n1: number } }>({});
  const [formSheet4, setFormSheet4] = useState<{ [key: string]: { n2: number; n1: number } }>({});

  // Fetch data realisasi tahunan dari database Supabase melalui API Route
  const fetchRealisasiData = async () => {
    setLoadingRealisasi(true);
    try {
      const res = await fetch('/api/rka/realisasi-tahunan');
      const json = await res.json();
      if (json.success) {
        setRealisasiTahunanList(json.data || []);
        setIsTableCreated(json.isTableCreated ?? true);
        initFormValues(json.data || []);
      }
    } catch (err) {
      console.error('Fetch rkat_realisasi_tahunan error:', err);
    } finally {
      setLoadingRealisasi(false);
    }
  };

  // Inisialisasi nilai form dari data DB (atau fallback ke default)
  const initFormValues = (dbData: any[]) => {
    const s3State: { [key: string]: { n2: number; n1: number } } = {};
    INITIAL_SHEET3_ITEMS.forEach(it => {
      const rowN2 = dbData.find(r => String(r.sheet_no) === '3' && r.kode_pos === it.key && Number(r.tahun) === 2024);
      const rowN1 = dbData.find(r => String(r.sheet_no) === '3' && r.kode_pos === it.key && Number(r.tahun) === 2025);
      s3State[it.key] = {
        n2: rowN2 ? Number(rowN2.nilai) : it.defN2,
        n1: rowN1 ? Number(rowN1.nilai) : it.defN1
      };
    });
    setFormSheet3(s3State);

    const s4State: { [key: string]: { n2: number; n1: number } } = {};
    INITIAL_SHEET4_ITEMS.forEach(it => {
      const rowN2 = dbData.find(r => String(r.sheet_no) === '4' && r.kode_pos === it.key && Number(r.tahun) === 2024);
      const rowN1 = dbData.find(r => String(r.sheet_no) === '4' && r.kode_pos === it.key && Number(r.tahun) === 2025);
      s4State[it.key] = {
        n2: rowN2 ? Number(rowN2.nilai) : it.defN2,
        n1: rowN1 ? Number(rowN1.nilai) : it.defN1
      };
    });
    setFormSheet4(s4State);
  };

  useEffect(() => {
    fetchRealisasiData();
  }, [tahunFilter]);

  // Handle perubahan input pada form editor
  const handleInputChange = (
    sheet: 'sheet3' | 'sheet4',
    key: string,
    field: 'n2' | 'n1',
    val: string
  ) => {
    // Bersihkan karakter non-digit kecuali tanda minus
    const cleanNum = Number(val.replace(/[^0-9.-]+/g, '')) || 0;
    if (sheet === 'sheet3') {
      setFormSheet3(prev => ({
        ...prev,
        [key]: {
          ...prev[key],
          [field]: cleanNum
        }
      }));
    } else {
      setFormSheet4(prev => ({
        ...prev,
        [key]: {
          ...prev[key],
          [field]: cleanNum
        }
      }));
    }
  };

  // Simpan data input form ke database Supabase via POST /api/rka/realisasi-tahunan
  const handleSaveToSupabase = async () => {
    setSavingRealisasi(true);
    try {
      const rowsToSave: any[] = [];

      // Susun rows Sheet 3
      INITIAL_SHEET3_ITEMS.forEach(it => {
        const valObj = formSheet3[it.key] || { n2: it.defN2, n1: it.defN1 };
        rowsToSave.push({
          tahun: 2024,
          jenis: 'realisasi',
          kategori: 'komponen_biaya',
          sheet_no: '3',
          kode_pos: it.key,
          nama_pos: it.label,
          sub_pos: '',
          sumber_dana: 'ALL',
          nilai: valObj.n2,
          keterangan: `Realisasi TA 2024 - ${it.label}`
        });
        rowsToSave.push({
          tahun: 2025,
          jenis: 'anggaran',
          kategori: 'komponen_biaya',
          sheet_no: '3',
          kode_pos: it.key,
          nama_pos: it.label,
          sub_pos: '',
          sumber_dana: 'ALL',
          nilai: valObj.n1,
          keterangan: `Anggaran TA 2025 - ${it.label}`
        });
      });

      // Susun rows Sheet 4
      INITIAL_SHEET4_ITEMS.forEach(it => {
        const valObj = formSheet4[it.key] || { n2: it.defN2, n1: it.defN1 };
        rowsToSave.push({
          tahun: 2024,
          jenis: 'realisasi',
          kategori: 'sumber_pembiayaan',
          sheet_no: '4',
          kode_pos: it.key,
          nama_pos: it.label,
          sub_pos: '',
          sumber_dana: it.kategori,
          nilai: valObj.n2,
          keterangan: `Realisasi TA 2024 - ${it.label}`
        });
        rowsToSave.push({
          tahun: 2025,
          jenis: 'anggaran',
          kategori: 'sumber_pembiayaan',
          sheet_no: '4',
          kode_pos: it.key,
          nama_pos: it.label,
          sub_pos: '',
          sumber_dana: it.kategori,
          nilai: valObj.n1,
          keterangan: `Anggaran TA 2025 - ${it.label}`
        });
      });

      const res = await fetch('/api/rka/realisasi-tahunan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ bulk: true, rows: rowsToSave })
      });

      const json = await res.json();
      if (!res.ok || !json.success) {
        throw new Error(json.error || 'Gagal menyimpan ke database');
      }

      toast.success('Data Realisasi N-2 & Anggaran N-1 berhasil disimpan ke database Supabase!');
      await fetchRealisasiData();
    } catch (err: any) {
      console.error('Save to Supabase error:', err);
      toast.error('Gagal menyimpan: ' + err.message);
    } finally {
      setSavingRealisasi(false);
    }
  };

  // Komputasi data untuk seluruh 5 sheet dengan memasukkan realisasiTahunanList dari database
  const template2Data: TemplateLaporan2Data = useMemo(() => {
    return computeTemplateLaporan2Data(dataList, penyesuaianList, realisasiTahunanList);
  }, [dataList, penyesuaianList, realisasiTahunanList]);

  const handleCopySql = () => {
    navigator.clipboard.writeText(SQL_MIGRATION_TEXT);
    setCopiedSql(true);
    toast.success('Script SQL migrasi berhasil disalin!');
    setTimeout(() => setCopiedSql(false), 2000);
  };

  // Handle Export Excel 5 Sheet Lengkap
  const handleExportExcelTemplate2 = () => {
    try {
      const wb = XLSX.utils.book_new();

      // 1. Sheet Pengesahan
      const s1Rows: any[] = [
        ['Tabel Pengesahan'],
        [],
        ['No', 'Sumber Pembiayaan', `Anggaran ${parseInt(tahunFilter) - 1 || 'N-1'}`, `Anggaran ${tahunFilter || 'N'}`]
      ];
      template2Data.sheet1.forEach(r => {
        s1Rows.push([r.no, r.sumber, r.anggaranN1, r.anggaranN]);
      });
      const ws1 = XLSX.utils.aoa_to_sheet(s1Rows);
      XLSX.utils.book_append_sheet(wb, ws1, '1. Pengesahan');

      // 2. Sheet 3. Ringkasan Biaya
      const s3Rows: any[] = [
        ['Ringkasan Biaya'],
        [],
        ['No', 'Komponen Biaya', 'Realisasi N-2', 'Anggaran N-1', `Anggaran ${tahunFilter || 'N'}`, `Proporsi Anggaran ${tahunFilter || 'N'}`]
      ];
      template2Data.sheet3.forEach(r => {
        s3Rows.push([r.no, r.komponen, r.realisasiN2, r.anggaranN1, r.anggaranN, `${r.proporsiN.toFixed(2)}%`]);
      });
      const ws3 = XLSX.utils.aoa_to_sheet(s3Rows);
      XLSX.utils.book_append_sheet(wb, ws3, '3. Ringkasan Biaya');

      // 3. Sheet 4. Ringkasan Sumber Pembiayaan
      const s4Rows: any[] = [
        ['Ringkasan Sumber Pembiayaan'],
        [],
        ['No', 'Sumber Pembiayaan', 'Realisasi N-2', 'Anggaran N-1', `Anggaran ${tahunFilter || 'N'}`, `Proporsi Anggaran ${tahunFilter || 'N'}`]
      ];
      template2Data.sheet4.forEach(r => {
        s4Rows.push([r.no, r.sumber, r.realisasiN2, r.anggaranN1, r.anggaranN, r.proporsiN ? `${r.proporsiN.toFixed(2)}%` : '']);
      });
      const ws4 = XLSX.utils.aoa_to_sheet(s4Rows);
      XLSX.utils.book_append_sheet(wb, ws4, '4. Ringkasan Sumber Pembiayaan');

      // 4. Sheet 6. Rincian Biaya
      const s6Rows: any[] = [
        ['Rincian Biaya'],
        [],
        ['No', 'Komponen Biaya', '(7734) Dukungan Manajemen', 'Alokasi BPPTNBH', 'PUAPT/PRPTNBH', 'PLN/HLN/RMP/SBSN/KPBU', 'Ditjen Dikti Lainnya', 'Unit Eselon I Lain', 'K/L Lain', 'Selain APBN', 'Total', 'Proporsi']
      ];
      template2Data.sheet6.forEach(r => {
        s6Rows.push([
          r.no,
          r.komponen,
          r.dukManajemen,
          r.bpptnbh,
          r.puapt,
          r.plnHln,
          r.diktiLain,
          r.eselonLain,
          r.klLain,
          r.selainApbn,
          r.total,
          `${r.proporsi.toFixed(2)}%`
        ]);
      });
      const ws6 = XLSX.utils.aoa_to_sheet(s6Rows);
      XLSX.utils.book_append_sheet(wb, ws6, '6. Rincian Biaya');

      // 5. Sheet 7. Rincian Sumber Pembiayaan
      const s7Rows: any[] = [
        ['Rincian Sumber Pembiayaan'],
        [],
        ['No', 'Sumber Pembiayaan', 'Realisasi N-2', 'Anggaran N-1', `Anggaran ${tahunFilter || 'N'}`, 'Proporsi']
      ];
      template2Data.sheet7.forEach(r => {
        s7Rows.push([r.no, r.sumber, r.realisasiN2, r.anggaranN1, r.anggaranN, r.proporsiN ? `${r.proporsiN.toFixed(2)}%` : '']);
      });
      const ws7 = XLSX.utils.aoa_to_sheet(s7Rows);
      XLSX.utils.book_append_sheet(wb, ws7, '7. Rincian Sumber Pembiayaan');

      XLSX.writeFile(wb, `Format_Pelaporan_PTNBH_Template_2_TA${tahunFilter}.xlsx`);
      toast.success('File Excel Format Evaluasi & Pelaporan PTN-BH (Template 2) berhasil diexport!');
    } catch (err: any) {
      console.error('Export Excel Template 2 error:', err);
      toast.error('Gagal export file Excel: ' + err.message);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* 1. HEADER INFO & STATS */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <Card className="rounded-2xl border-blue-200/80 shadow-2xs bg-gradient-to-br from-blue-50/50 to-white">
          <CardContent className="p-4 space-y-1">
            <span className="text-[10px] font-bold text-blue-600 uppercase tracking-wider block">
              1. Rupiah Murni (Dukman)
            </span>
            <div className="text-base sm:text-lg font-black text-blue-950 font-mono">
              Rp {formatRp(template2Data.totals.rupiahMurni)}
            </div>
            <div className="text-[10px] text-gray-500 font-medium">DIPA Gaji &amp; Tunjangan PNS</div>
          </CardContent>
        </Card>

        <Card className="rounded-2xl border-indigo-200/80 shadow-2xs bg-gradient-to-br from-indigo-50/50 to-white">
          <CardContent className="p-4 space-y-1">
            <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block">
              2. Alokasi BPPTNBH
            </span>
            <div className="text-base sm:text-lg font-black text-indigo-950 font-mono">
              Rp {formatRp(template2Data.totals.bpptnbh)}
            </div>
            <div className="text-[10px] text-gray-500 font-medium">Bantuan Pendanaan PTN-BH</div>
          </CardContent>
        </Card>

        <Card className="rounded-2xl border-emerald-200/80 shadow-2xs bg-gradient-to-br from-emerald-50/50 to-white">
          <CardContent className="p-4 space-y-1">
            <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider block">
              8. Selain APBN
            </span>
            <div className="text-base sm:text-lg font-black text-emerald-950 font-mono">
              Rp {formatRp(template2Data.totals.selainApbn)}
            </div>
            <div className="text-[10px] text-gray-500 font-medium">Dana Masyarakat Universitas</div>
          </CardContent>
        </Card>

        <Card className="rounded-2xl border-purple-200/80 shadow-2xs bg-gradient-to-br from-purple-50/50 to-white">
          <CardContent className="p-4 space-y-1">
            <span className="text-[10px] font-bold text-purple-600 uppercase tracking-wider block">
              TOTAL ALOKASI (TA {tahunFilter})
            </span>
            <div className="text-base sm:text-lg font-black text-purple-950 font-mono">
              Rp {formatRp(template2Data.totals.totalAnggaranN)}
            </div>
            <div className="text-[10px] text-gray-500 font-medium">APBN + Selain APBN</div>
          </CardContent>
        </Card>
      </div>

      {/* 2. SUB-SHEET SWITCHER & EXPORT BUTTON */}
      <Card className="rounded-2xl border-gray-200/80 shadow-xs overflow-hidden">
        <CardHeader className="bg-gray-50/60 p-4 sm:p-5 border-b border-gray-100 flex flex-col md:flex-row md:items-center justify-between gap-3">
          <div>
            <div className="flex items-center gap-2">
              <CardTitle className="text-sm sm:text-base font-black text-gray-900 flex items-center gap-2">
                <Landmark size={18} className="text-indigo-600" />
                <span>Format Evaluasi &amp; Pelaporan PTN-BH (Template 2)</span>
              </CardTitle>
              <Badge 
                variant="outline" 
                className={`text-[10px] font-bold ${
                  isTableCreated 
                    ? 'bg-emerald-50 text-emerald-700 border-emerald-300' 
                    : 'bg-amber-50 text-amber-700 border-amber-300'
                }`}
              >
                <Database size={11} className="mr-1" />
                {isTableCreated ? 'DB Supabase: rkat_realisasi_tahunan' : 'DB Standby (Default Template)'}
              </Badge>
            </div>
            <CardDescription className="text-xs text-gray-500 font-medium mt-0.5">
              Sesuai template baku &quot;template laporan 2.xlsx&quot; yang memuat 5 lembar kerja laporan Kementerian RI
            </CardDescription>
          </div>

          <div className="flex items-center gap-2 self-start md:self-auto shrink-0 flex-wrap">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                setShowDbModal(true);
                setModalTab('input_editor');
              }}
              className="h-9 px-3.5 text-xs font-bold text-indigo-700 border-indigo-200 bg-indigo-50/50 hover:bg-indigo-100 rounded-xl shadow-2xs gap-1.5 cursor-pointer"
            >
              <Edit3 size={14} className="text-indigo-600" />
              <span>Input &amp; Kelola Realisasi</span>
            </Button>

            <Button
              type="button"
              onClick={handleExportExcelTemplate2}
              className="h-9 px-4 text-xs font-bold bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl shadow-xs transition-all flex items-center gap-2 cursor-pointer"
            >
              <Download size={15} />
              <span>Export Excel 5 Sheet (Template 2)</span>
            </Button>
          </div>
        </CardHeader>

        <CardContent className="p-4 sm:p-5 space-y-4">
          {/* SHEET TAB BUTTONS */}
          <div className="flex flex-wrap items-center gap-1.5 bg-gray-100 p-1.5 rounded-xl border border-gray-200 text-xs font-bold overflow-x-auto">
            <button
              type="button"
              onClick={() => setActiveSheet('pengesahan')}
              className={`px-3.5 py-2 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 whitespace-nowrap ${
                activeSheet === 'pengesahan'
                  ? 'bg-white text-indigo-700 shadow-xs font-black'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-200/60'
              }`}
            >
              <FileText size={14} className={activeSheet === 'pengesahan' ? 'text-indigo-600' : 'text-gray-400'} />
              <span>1. Pengesahan</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveSheet('ringkasan_biaya')}
              className={`px-3.5 py-2 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 whitespace-nowrap ${
                activeSheet === 'ringkasan_biaya'
                  ? 'bg-white text-indigo-700 shadow-xs font-black'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-200/60'
              }`}
            >
              <Layers size={14} className={activeSheet === 'ringkasan_biaya' ? 'text-indigo-600' : 'text-gray-400'} />
              <span>3. Ringkasan Biaya</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveSheet('ringkasan_sumber')}
              className={`px-3.5 py-2 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 whitespace-nowrap ${
                activeSheet === 'ringkasan_sumber'
                  ? 'bg-white text-indigo-700 shadow-xs font-black'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-200/60'
              }`}
            >
              <Wallet size={14} className={activeSheet === 'ringkasan_sumber' ? 'text-indigo-600' : 'text-gray-400'} />
              <span>4. Ringkasan Sumber Pembiayaan</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveSheet('rincian_biaya')}
              className={`px-3.5 py-2 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 whitespace-nowrap ${
                activeSheet === 'rincian_biaya'
                  ? 'bg-white text-indigo-700 shadow-xs font-black'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-200/60'
              }`}
            >
              <DollarSign size={14} className={activeSheet === 'rincian_biaya' ? 'text-indigo-600' : 'text-gray-400'} />
              <span>6. Rincian Biaya</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveSheet('rincian_sumber')}
              className={`px-3.5 py-2 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 whitespace-nowrap ${
                activeSheet === 'rincian_sumber'
                  ? 'bg-white text-indigo-700 shadow-xs font-black'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-200/60'
              }`}
            >
              <Building2 size={14} className={activeSheet === 'rincian_sumber' ? 'text-indigo-600' : 'text-gray-400'} />
              <span>7. Rincian Sumber Pembiayaan</span>
            </button>
          </div>

          {/* TABEL SHEET 1: 1. PENGESAHAN */}
          {activeSheet === 'pengesahan' && (
            <div className="border border-gray-200 rounded-xl overflow-hidden shadow-2xs">
              <div className="bg-slate-800 text-white px-4 py-3 font-bold text-xs flex items-center justify-between">
                <span>TABEL PENGESAHAN EVALUASI ANGGARAN PTN-BH</span>
                <span className="text-[11px] text-slate-300 font-mono">Format Kementerian</span>
              </div>
              <Table>
                <TableHeader>
                  <TableRow className="bg-slate-100 hover:bg-slate-100 text-[11px] font-black text-slate-800">
                    <TableHead className="w-16 text-center">No</TableHead>
                    <TableHead>Sumber Pembiayaan</TableHead>
                    <TableHead className="text-right w-56">Anggaran {parseInt(tahunFilter) - 1 || 'N-1'}</TableHead>
                    <TableHead className="text-right w-56">Anggaran {tahunFilter || 'N'}</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody className="text-xs divide-y divide-gray-100">
                  {template2Data.sheet1.map((r, idx) => {
                    const isTotal = r.no === 'TOTAL';
                    return (
                      <TableRow 
                        key={idx}
                        className={isTotal ? 'bg-indigo-50/70 font-black text-indigo-950' : 'hover:bg-gray-50/80 font-medium'}
                      >
                        <TableCell className="text-center font-bold text-gray-500">{r.no}</TableCell>
                        <TableCell className={isTotal ? 'font-black' : 'font-semibold text-gray-900'}>{r.sumber}</TableCell>
                        <TableCell className="text-right font-mono font-bold text-gray-700">
                          Rp {formatRp(r.anggaranN1)}
                        </TableCell>
                        <TableCell className={`text-right font-mono font-black ${isTotal ? 'text-indigo-900' : 'text-gray-900'}`}>
                          Rp {formatRp(r.anggaranN)}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}

          {/* TABEL SHEET 2: 3. RINGKASAN BIAYA */}
          {activeSheet === 'ringkasan_biaya' && (
            <div className="border border-gray-200 rounded-xl overflow-hidden shadow-2xs">
              <div className="bg-slate-800 text-white px-4 py-3 font-bold text-xs flex items-center justify-between">
                <span>RINGKASAN 8 KOMPONEN BIAYA PTN-BH</span>
                <span className="text-[11px] text-slate-300 font-mono">Evaluasi Komponen Biaya</span>
              </div>
              <Table>
                <TableHeader>
                  <TableRow className="bg-slate-100 hover:bg-slate-100 text-[11px] font-black text-slate-800">
                    <TableHead className="w-12 text-center">No</TableHead>
                    <TableHead>Komponen Biaya</TableHead>
                    <TableHead className="text-right w-44">Realisasi 2024 (N-2)</TableHead>
                    <TableHead className="text-right w-44">Anggaran 2025 (N-1)</TableHead>
                    <TableHead className="text-right w-52">Anggaran N (TA {tahunFilter})</TableHead>
                    <TableHead className="text-right w-32">Proporsi (%)</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody className="text-xs divide-y divide-gray-100">
                  {template2Data.sheet3.map((r, idx) => {
                    const isTotal = r.no === 'Total';
                    return (
                      <TableRow 
                        key={idx}
                        className={isTotal ? 'bg-indigo-50/70 font-black text-indigo-950' : 'hover:bg-gray-50/80 font-medium'}
                      >
                        <TableCell className="text-center font-bold text-gray-500">{r.no}</TableCell>
                        <TableCell className={isTotal ? 'font-black' : 'font-semibold text-gray-900'}>{r.komponen}</TableCell>
                        <TableCell className="text-right font-mono font-semibold text-gray-700">
                          {r.realisasiN2 > 0 ? `Rp ${formatRp(r.realisasiN2)}` : '-'}
                        </TableCell>
                        <TableCell className="text-right font-mono font-semibold text-gray-700">
                          {r.anggaranN1 > 0 ? `Rp ${formatRp(r.anggaranN1)}` : '-'}
                        </TableCell>
                        <TableCell className={`text-right font-mono font-black ${isTotal ? 'text-indigo-900' : 'text-gray-900'}`}>
                          Rp {formatRp(r.anggaranN)}
                        </TableCell>
                        <TableCell className="text-right font-mono font-bold text-indigo-700">
                          {r.proporsiN.toFixed(2)}%
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}

          {/* TABEL SHEET 3: 4. RINGKASAN SUMBER PEMBIAYAAN */}
          {activeSheet === 'ringkasan_sumber' && (
            <div className="border border-gray-200 rounded-xl overflow-hidden shadow-2xs">
              <div className="bg-slate-800 text-white px-4 py-3 font-bold text-xs flex items-center justify-between">
                <span>RINGKASAN SUMBER PEMBIAYAAN (APBN VS SELAIN APBN)</span>
                <span className="text-[11px] text-slate-300 font-mono">Evaluasi Sumber Dana</span>
              </div>
              <Table>
                <TableHeader>
                  <TableRow className="bg-slate-100 hover:bg-slate-100 text-[11px] font-black text-slate-800">
                    <TableHead className="w-12 text-center">No</TableHead>
                    <TableHead>Sumber Pembiayaan</TableHead>
                    <TableHead className="text-right w-44">Realisasi N-2</TableHead>
                    <TableHead className="text-right w-44">Anggaran N-1</TableHead>
                    <TableHead className="text-right w-52">Anggaran N (TA {tahunFilter})</TableHead>
                    <TableHead className="text-right w-32">Proporsi (%)</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody className="text-xs divide-y divide-gray-100">
                  {template2Data.sheet4.map((r, idx) => {
                    const isTotal = r.kategori === 'TOTAL';
                    const isHeader = r.isHeader;
                    return (
                      <TableRow 
                        key={idx}
                        className={
                          isTotal 
                            ? 'bg-purple-100/70 font-black text-purple-950' 
                            : isHeader 
                            ? 'bg-slate-200/70 font-black text-slate-900' 
                            : 'hover:bg-gray-50/80 font-medium'
                        }
                      >
                        <TableCell className="text-center font-bold text-gray-500">{r.no}</TableCell>
                        <TableCell className={isHeader ? 'font-black tracking-wide' : 'font-semibold text-gray-900 pl-6'}>
                          {r.sumber}
                        </TableCell>
                        <TableCell className="text-right font-mono font-semibold text-gray-700">
                          {r.realisasiN2 > 0 ? `Rp ${formatRp(r.realisasiN2)}` : '-'}
                        </TableCell>
                        <TableCell className="text-right font-mono font-semibold text-gray-700">
                          {r.anggaranN1 > 0 ? `Rp ${formatRp(r.anggaranN1)}` : '-'}
                        </TableCell>
                        <TableCell className={`text-right font-mono font-black ${isTotal ? 'text-purple-950' : isHeader ? 'text-indigo-900' : 'text-gray-900'}`}>
                          {r.anggaranN > 0 ? `Rp ${formatRp(r.anggaranN)}` : '-'}
                        </TableCell>
                        <TableCell className="text-right font-mono font-bold text-indigo-700">
                          {r.proporsiN > 0 ? `${r.proporsiN.toFixed(2)}%` : '-'}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}

          {/* TABEL SHEET 4: 6. RINCIAN BIAYA (MATRIX) */}
          {activeSheet === 'rincian_biaya' && (
            <div className="border border-gray-200 rounded-xl overflow-x-auto shadow-2xs">
              <div className="bg-slate-800 text-white px-4 py-3 font-bold text-xs flex items-center justify-between min-w-[1000px]">
                <span>RINCIAN 8 KOMPONEN BIAYA PER SUMBER PEMBIAYAAN</span>
                <span className="text-[11px] text-slate-300 font-mono">Matriks Alokasi Dana</span>
              </div>
              <Table className="min-w-[1000px]">
                <TableHeader>
                  <TableRow className="bg-slate-100 hover:bg-slate-100 text-[10px] font-black text-slate-800 divide-x divide-gray-200">
                    <TableHead className="w-10 text-center">No</TableHead>
                    <TableHead className="w-60">Komponen Biaya</TableHead>
                    <TableHead className="text-right w-32">(7734) Dukman</TableHead>
                    <TableHead className="text-right w-32">BPPTNBH</TableHead>
                    <TableHead className="text-right w-24">PUAPT</TableHead>
                    <TableHead className="text-right w-32">PLN / HLN</TableHead>
                    <TableHead className="text-right w-32">Dikti Lainnya</TableHead>
                    <TableHead className="text-right w-32">K/L Lainnya</TableHead>
                    <TableHead className="text-right w-36">Selain APBN</TableHead>
                    <TableHead className="text-right w-36 bg-indigo-50 font-black">TOTAL</TableHead>
                    <TableHead className="text-right w-20">Proporsi</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody className="text-xs divide-y divide-gray-100">
                  {template2Data.sheet6.map((r, idx) => (
                    <TableRow key={idx} className="hover:bg-gray-50/80 divide-x divide-gray-100">
                      <TableCell className="text-center font-bold text-gray-500">{r.no}</TableCell>
                      <TableCell className="font-semibold text-gray-900">{r.komponen}</TableCell>
                      <TableCell className="text-right font-mono text-blue-900 font-semibold">{r.dukManajemen > 0 ? formatRp(r.dukManajemen) : '-'}</TableCell>
                      <TableCell className="text-right font-mono text-indigo-900 font-semibold">{r.bpptnbh > 0 ? formatRp(r.bpptnbh) : '-'}</TableCell>
                      <TableCell className="text-right font-mono text-gray-400">{r.puapt > 0 ? formatRp(r.puapt) : '-'}</TableCell>
                      <TableCell className="text-right font-mono text-teal-900 font-semibold">{r.plnHln > 0 ? formatRp(r.plnHln) : '-'}</TableCell>
                      <TableCell className="text-right font-mono text-orange-900 font-semibold">{r.diktiLain > 0 ? formatRp(r.diktiLain) : '-'}</TableCell>
                      <TableCell className="text-right font-mono text-amber-900 font-semibold">{r.klLain > 0 ? formatRp(r.klLain) : '-'}</TableCell>
                      <TableCell className="text-right font-mono text-emerald-900 font-semibold">{r.selainApbn > 0 ? formatRp(r.selainApbn) : '-'}</TableCell>
                      <TableCell className="text-right font-mono font-black text-indigo-950 bg-indigo-50/50">
                        Rp {formatRp(r.total)}
                      </TableCell>
                      <TableCell className="text-right font-mono font-bold text-indigo-700">
                        {r.proporsi.toFixed(2)}%
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}

          {/* TABEL SHEET 5: 7. RINCIAN SUMBER PEMBIAYAAN */}
          {activeSheet === 'rincian_sumber' && (
            <div className="border border-gray-200 rounded-xl overflow-hidden shadow-2xs">
              <div className="bg-slate-800 text-white px-4 py-3 font-bold text-xs flex items-center justify-between">
                <span>RINCIAN SUMBER PEMBIAYAAN (SUB-RINCIAN APBN &amp; SELAIN APBN)</span>
                <span className="text-[11px] text-slate-300 font-mono">Format Evaluasi Rinci</span>
              </div>
              <Table>
                <TableHeader>
                  <TableRow className="bg-slate-100 hover:bg-slate-100 text-[11px] font-black text-slate-800">
                    <TableHead className="w-12 text-center">No</TableHead>
                    <TableHead>Sumber Pembiayaan &amp; Sub-Item</TableHead>
                    <TableHead className="text-right w-44">Realisasi N-2</TableHead>
                    <TableHead className="text-right w-44">Anggaran N-1</TableHead>
                    <TableHead className="text-right w-52">Anggaran N (TA {tahunFilter})</TableHead>
                    <TableHead className="text-right w-28">Proporsi</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody className="text-xs divide-y divide-gray-100">
                  {template2Data.sheet7.map((r, idx) => {
                    const isTotal = r.kategori === 'TOTAL';
                    const isHeader = r.isHeader;
                    const isSub = r.isSubItem;
                    return (
                      <TableRow 
                        key={idx}
                        className={
                          isTotal 
                            ? 'bg-purple-100/70 font-black text-purple-950' 
                            : isHeader 
                            ? 'bg-slate-200/70 font-black text-slate-900' 
                            : isSub 
                            ? 'bg-gray-50/40 text-gray-700 italic' 
                            : 'hover:bg-gray-50/80 font-medium'
                        }
                      >
                        <TableCell className="text-center font-bold text-gray-500">{r.no}</TableCell>
                        <TableCell className={isHeader ? 'font-black tracking-wide' : isSub ? 'pl-8 text-gray-600' : 'font-semibold text-gray-900 pl-4'}>
                          {r.sumber}
                        </TableCell>
                        <TableCell className="text-right font-mono font-semibold text-gray-700">
                          {r.realisasiN2 > 0 ? `Rp ${formatRp(r.realisasiN2)}` : '-'}
                        </TableCell>
                        <TableCell className="text-right font-mono font-semibold text-gray-700">
                          {r.anggaranN1 > 0 ? `Rp ${formatRp(r.anggaranN1)}` : '-'}
                        </TableCell>
                        <TableCell className={`text-right font-mono font-black ${isHeader ? 'text-indigo-900' : 'text-gray-900'}`}>
                          {r.anggaranN > 0 ? `Rp ${formatRp(r.anggaranN)}` : '-'}
                        </TableCell>
                        <TableCell className="text-right font-mono font-bold text-indigo-700">
                          {r.proporsiN > 0 ? `${r.proporsiN.toFixed(2)}%` : '-'}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* 3. DIALOG MODAL: INPUT & EDIT REALISASI TAHUNAN */}
      <Dialog open={showDbModal} onOpenChange={setShowDbModal}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <div className="flex items-center justify-between gap-3 border-b border-gray-100 pb-3">
              <div className="flex items-center gap-2.5">
                <div className="p-2.5 bg-indigo-50 text-indigo-700 rounded-xl">
                  <Database size={22} />
                </div>
                <div>
                  <DialogTitle className="text-base font-black text-gray-900">
                    Input &amp; Pengelolaan Realisasi Tahunan (Supabase)
                  </DialogTitle>
                  <DialogDescription className="text-xs text-gray-500 font-medium">
                    Tabel <code className="text-indigo-600 font-bold">public.rkat_realisasi_tahunan</code> untuk kolom Realisasi N-2 dan Anggaran N-1
                  </DialogDescription>
                </div>
              </div>
              <Badge className={isTableCreated ? "bg-emerald-100 text-emerald-800 border-emerald-300" : "bg-amber-100 text-amber-800 border-amber-300"}>
                {isTableCreated ? 'Tabel Terhubung' : 'Perlu Migrasi SQL'}
              </Badge>
            </div>
          </DialogHeader>

          {/* TAB PILIHAN MODAL: INPUT EDITOR vs DB INFO */}
          <div className="flex items-center gap-2 border-b border-gray-200 pb-2 pt-1">
            <button
              type="button"
              onClick={() => setModalTab('input_editor')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                modalTab === 'input_editor'
                  ? 'bg-indigo-600 text-white shadow-xs'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-100'
              }`}
            >
              <Edit3 size={13} />
              <span>Form Input / Edit Angka</span>
            </button>
            <button
              type="button"
              onClick={() => setModalTab('db_info')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                modalTab === 'db_info'
                  ? 'bg-indigo-600 text-white shadow-xs'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-100'
              }`}
            >
              <Server size={13} />
              <span>Info Struktur &amp; Script SQL</span>
            </button>
          </div>

          {/* KONTEN TAB 1: FORM INPUT EDITOR */}
          {modalTab === 'input_editor' && (
            <div className="space-y-4 pt-1">
              <div className="flex items-center justify-between gap-2 flex-wrap">
                <div className="flex items-center gap-1.5 bg-gray-100 p-1 rounded-xl text-xs font-bold">
                  <button
                    type="button"
                    onClick={() => setEditorSubSheet('sheet3')}
                    className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                      editorSubSheet === 'sheet3' ? 'bg-white text-indigo-700 shadow-xs font-black' : 'text-gray-600'
                    }`}
                  >
                    Sheet 3: 8 Komponen Biaya
                  </button>
                  <button
                    type="button"
                    onClick={() => setEditorSubSheet('sheet4')}
                    className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                      editorSubSheet === 'sheet4' ? 'bg-white text-indigo-700 shadow-xs font-black' : 'text-gray-600'
                    }`}
                  >
                    Sheet 4: Sumber Pembiayaan
                  </button>
                </div>

                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => initFormValues(realisasiTahunanList)}
                    className="h-8 rounded-xl text-xs font-bold text-gray-600 gap-1 cursor-pointer"
                  >
                    <RotateCcw size={12} />
                    <span>Reset</span>
                  </Button>
                  <Button
                    type="button"
                    size="sm"
                    onClick={handleSaveToSupabase}
                    disabled={savingRealisasi}
                    className="h-8 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold gap-1.5 shadow-xs cursor-pointer"
                  >
                    {savingRealisasi ? <RefreshCw size={12} className="animate-spin" /> : <Save size={12} />}
                    <span>{savingRealisasi ? 'Menyimpan...' : 'Simpan ke Supabase'}</span>
                  </Button>
                </div>
              </div>

              {/* TABEL INPUT SHEET 3 */}
              {editorSubSheet === 'sheet3' && (
                <div className="border border-gray-200 rounded-xl overflow-hidden shadow-2xs">
                  <div className="bg-slate-800 text-white px-3 py-2 text-xs font-bold flex items-center justify-between">
                    <span>EDIT REALISASI &amp; ANGGARAN: 8 KOMPONEN BIAYA (SHEET 3)</span>
                    <span className="text-[11px] text-slate-300 font-mono">Simpan langsung ke Supabase</span>
                  </div>
                  <Table>
                    <TableHeader>
                      <TableRow className="bg-slate-100 text-[11px] font-black text-slate-800">
                        <TableHead className="w-10 text-center">No</TableHead>
                        <TableHead className="w-64">Komponen Biaya</TableHead>
                        <TableHead className="w-56 text-right">Realisasi 2024 (N-2) (Rp)</TableHead>
                        <TableHead className="w-56 text-right">Anggaran 2025 (N-1) (Rp)</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody className="text-xs divide-y divide-gray-100">
                      {INITIAL_SHEET3_ITEMS.map((item) => {
                        const curVal = formSheet3[item.key] || { n2: item.defN2, n1: item.defN1 };
                        return (
                          <TableRow key={item.key} className="hover:bg-gray-50/60">
                            <TableCell className="text-center font-bold text-gray-500">{item.no}</TableCell>
                            <TableCell className="font-semibold text-gray-900">{item.label}</TableCell>
                            <TableCell className="text-right">
                              <Input
                                type="number"
                                value={curVal.n2}
                                onChange={(e) => handleInputChange('sheet3', item.key, 'n2', e.target.value)}
                                className="h-8 text-right font-mono font-bold text-xs"
                              />
                              <div className="text-[10px] text-gray-500 font-mono text-right mt-0.5">
                                Rp {formatRp(curVal.n2)}
                              </div>
                            </TableCell>
                            <TableCell className="text-right">
                              <Input
                                type="number"
                                value={curVal.n1}
                                onChange={(e) => handleInputChange('sheet3', item.key, 'n1', e.target.value)}
                                className="h-8 text-right font-mono font-bold text-xs"
                              />
                              <div className="text-[10px] text-gray-500 font-mono text-right mt-0.5">
                                Rp {formatRp(curVal.n1)}
                              </div>
                            </TableCell>
                          </TableRow>
                        );
                      })}
                    </TableBody>
                  </Table>
                </div>
              )}

              {/* TABEL INPUT SHEET 4 */}
              {editorSubSheet === 'sheet4' && (
                <div className="border border-gray-200 rounded-xl overflow-hidden shadow-2xs">
                  <div className="bg-slate-800 text-white px-3 py-2 text-xs font-bold flex items-center justify-between">
                    <span>EDIT REALISASI &amp; ANGGARAN: SUMBER PEMBIAYAAN (SHEET 4)</span>
                    <span className="text-[11px] text-slate-300 font-mono">APBN &amp; Selain APBN</span>
                  </div>
                  <Table>
                    <TableHeader>
                      <TableRow className="bg-slate-100 text-[11px] font-black text-slate-800">
                        <TableHead className="w-10 text-center">No</TableHead>
                        <TableHead className="w-64">Sumber Pembiayaan</TableHead>
                        <TableHead className="w-24 text-center">Kategori</TableHead>
                        <TableHead className="w-52 text-right">Realisasi 2024 (N-2) (Rp)</TableHead>
                        <TableHead className="w-52 text-right">Anggaran 2025 (N-1) (Rp)</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody className="text-xs divide-y divide-gray-100">
                      {INITIAL_SHEET4_ITEMS.map((item) => {
                        const curVal = formSheet4[item.key] || { n2: item.defN2, n1: item.defN1 };
                        return (
                          <TableRow key={item.key} className="hover:bg-gray-50/60">
                            <TableCell className="text-center font-bold text-gray-500">{item.no}</TableCell>
                            <TableCell className="font-semibold text-gray-900">{item.label}</TableCell>
                            <TableCell className="text-center">
                              <Badge variant="outline" className={`text-[9px] font-bold ${item.kategori === 'APBN' ? 'bg-blue-50 text-blue-700' : 'bg-emerald-50 text-emerald-700'}`}>
                                {item.kategori}
                              </Badge>
                            </TableCell>
                            <TableCell className="text-right">
                              <Input
                                type="number"
                                value={curVal.n2}
                                onChange={(e) => handleInputChange('sheet4', item.key, 'n2', e.target.value)}
                                className="h-8 text-right font-mono font-bold text-xs"
                              />
                              <div className="text-[10px] text-gray-500 font-mono text-right mt-0.5">
                                Rp {formatRp(curVal.n2)}
                              </div>
                            </TableCell>
                            <TableCell className="text-right">
                              <Input
                                type="number"
                                value={curVal.n1}
                                onChange={(e) => handleInputChange('sheet4', item.key, 'n1', e.target.value)}
                                className="h-8 text-right font-mono font-bold text-xs"
                              />
                              <div className="text-[10px] text-gray-500 font-mono text-right mt-0.5">
                                Rp {formatRp(curVal.n1)}
                              </div>
                            </TableCell>
                          </TableRow>
                        );
                      })}
                    </TableBody>
                  </Table>
                </div>
              )}

              <div className="flex items-center justify-between pt-2 border-t border-gray-100">
                <span className="text-[11px] text-gray-500 font-medium italic">
                  💡 Angka yang disimpan akan langsung mengupdate tampilan Sheet 3, 4, 6, dan 7 secara real-time.
                </span>
                <Button
                  type="button"
                  size="sm"
                  onClick={handleSaveToSupabase}
                  disabled={savingRealisasi}
                  className="h-8 px-4 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold gap-1.5 shadow-xs cursor-pointer"
                >
                  {savingRealisasi ? <RefreshCw size={12} className="animate-spin" /> : <Save size={12} />}
                  <span>Simpan Semua Perubahan</span>
                </Button>
              </div>
            </div>
          )}

          {/* KONTEN TAB 2: DB INFO & SCRIPT SQL */}
          {modalTab === 'db_info' && (
            <div className="space-y-4 pt-1">
              <div className="p-3 bg-blue-50/70 border border-blue-200 rounded-xl text-xs text-blue-900 flex items-start gap-2.5">
                <Info size={16} className="text-blue-600 shrink-0 mt-0.5" />
                <div className="space-y-1">
                  <p className="font-semibold">Informasi Tabel Database <code className="font-mono bg-blue-100 px-1 py-0.5 rounded">rkat_realisasi_tahunan</code>:</p>
                  <p className="text-[11px] text-blue-800">
                    Menyimpan angka agregat makro Realisasi Tahunan (N-2) dan Anggaran Tahunan (N-1). Tabel ini telah aktif di Supabase Anda dan terhubung secara otomatis ke modul evaluasi laporan kementerian.
                  </p>
                </div>
              </div>

              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-gray-700">Script SQL Migration Lengkap:</span>
                  <span className="text-[11px] text-gray-500 font-mono">File: supabase_rkat_realisasi_tahunan_migration.sql</span>
                </div>
                <div className="p-3 bg-slate-900 text-emerald-400 font-mono text-[11px] rounded-xl overflow-x-auto max-h-52 border border-slate-800 shadow-inner">
                  <pre>{SQL_MIGRATION_TEXT}</pre>
                </div>
              </div>

              <div className="flex items-center justify-between gap-2 pt-2 border-t border-gray-100">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={fetchRealisasiData}
                  disabled={loadingRealisasi}
                  className="h-8 rounded-xl text-xs font-bold gap-1.5 cursor-pointer"
                >
                  <RefreshCw size={13} className={loadingRealisasi ? 'animate-spin' : ''} />
                  <span>Cek Ulang Status Koneksi</span>
                </Button>

                <Button
                  type="button"
                  size="sm"
                  onClick={handleCopySql}
                  className="h-8 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs gap-1.5 shadow-xs cursor-pointer"
                >
                  {copiedSql ? <Check size={13} /> : <Copy size={13} />}
                  <span>{copiedSql ? 'Tersalin!' : 'Salin Script SQL Lengkap'}</span>
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
